Setup env
BuildForSDG/Team-108-Frontend pull request #5
Opened 2020-05-11 09:07 UTC by spaceofmiah

## Description
Setup working environment with react 

Fixes #(issue number 4) #4

## How Has This Been Tested?
This feature is well tested as running `npm start` launches web server and renders a react component without throwing any error or warning

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-11 16:44 UTC, ezekieltech requested changes
The package.json file did not match the standards as prescribed by Codacy.

Also index.html file needs some additional meta description

2020-05-11 16:44 UTC, ezekieltech commented on README.md
We need to create this as an Issue so that we will have a standard README.md

2020-05-11 16:44 UTC, ezekieltech commented on package.json
>      "test:watch": "jest --watch",
There's a quite some feedback from Codacy on this file. Many have to standard spacing and all. You should check it out.

2020-05-11 16:44 UTC, ezekieltech commented on public/index.html
> +      <meta charset = "UTF-8">
We may need more meta description.
`<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0">`
`<meta charset="utf-8">`
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`
`<meta name="description" content="">`

2020-05-16 00:10 UTC, Chukwuedo approved these changes
No further comments

2020-05-16 12:57 UTC, ezekieltech approved these changes

2020-05-16 19:25 UTC, Stephen-Kamau approved these changes

2020-05-16 23:48 UTC, merged